# -*- coding: utf-8 -*-
"""EGECAN_DOGAROGLU_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bXDbu3Q2xaylaI16UgA5625DgdwLR5Iu

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is."""

# In mathematics and computer science and algorithm is a system of steps to solve a problem.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

b = " Within brute force regular design all elements and possible outcomes of design work are thought through and computed beforehand, whereas in algorithmic design there would be simple rules from which the outcomes would vary later depending on these rules. In an algorithmic design outcome is expected to have a more naturalistic harmony."

print(len(b.split()))

"""In 100 words meditate on how a new approach on design such as one that is algorithmic could affect your work practice."""

a=" When I want to create real-time designs or endless loops it's important to not compute every step myself rather set some rules so the computer can do that for me. Also I'm more interested in generative design, because for me the intuition behind it is taking something beautiful like nature, human behaviour or music (as in audio-visual works) as a baseline and creating something else out of it, in other words giving the situation a new perspective, creating a new perception that noone else has never thought of. If we think humans as combination of algorithms like it was claimed in Homo Deus, then each individual's or creation's perception is unique depending on its unique facts and relations of those fact with each other is the thing that is creating our perception in life. I think it's highly exciting to be able to create something like this."

print(len(a.split()))

"""Create a python dictionary for your name surname and year of birth."""

dict_ege = {"name": "ege can", "surname":"doğaroğlu", "year of birth":"1996"}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if dict_ege["name"][0] == "a" : 
  print("my initial is a!")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(dict_ege["surname"])%3 == 0 : 
  print("it is divisible")
else : 
  print ("not divisible")

"""Change your year of birth to 2678."""

dict_ege["year of birth"] = "2678"

print(dict_ege["year of birth"])

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""